### ISSUE TITLE
CodeBuildProjectTriggersFilterGroups should be list of lists

### ISSUE THREAD

**Issue by dmateusp** [mbj/stratosphere#140]
Hi there, stratosphere seems to have a wrong spec here:

AWS Cloudformation docs FilterGroups is defined as a `list of lists` of WebhookFilter objects (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projecttriggers.html) but in stratosphere it's a list of WebhookFilter (https://github.com/freckle/stratosphere/blob/14efb6e934263ea873e10c152f354f637a4a6520/library-gen/Stratosphere/ResourceProperties/CodeBuildProjectProjectTriggers.hs#L17) so it produces an invalid Cloudformation template

The result in CloudFormation would look like
```
FilterGroups:
        - - Type: EVENT
            Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
          - Type: BASE_REF
            Pattern: ^refs/heads/master$
            ExcludeMatchedPattern: false
        - - Type: EVENT
            Pattern: PUSH
          - Type: HEAD_REF
```

while in stratosphere:

```
FilterGroups:
    - Type: EVENT
       Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
```

resulting error in cloudformation: `Property validation failure: [Value of property {/Triggers/FilterGroups/0} does not match type {Array}`
